
# Fill in this variables
VARIABLES:

  # Note: leave empty if not using API public/private key
  API_PUBLIC_KEY:
  API_SECRET_KEY:
  EXCHANGE:


# These are the messages sent to the user
MESSAGES:

  message_1:
    "\n---\nPlease enter exchange to pull OHLCV data from:\n"
  message_1_error_handler:
    "---\n\nERROR: Exchange `%s`  is unavailable.\n\n"

  message_2:
    "---\nPlease enter API public key (press `Enter` if None):  "

  message_3:
    "---\nPlease enter API private key (press `Enter` if None):  "

  message_4: >

    ---

    Please enter your candle interval as an abbreviation.

    NOTE: quotes are not needed in your entry.

    Examples:  "5m", "1h", "4h", "1d"
