
# Fill in this variables (not required)
VARIABLES:

  EXCHANGE: ""
  # NOTE: leave empty if not using API public/private key (TODO- add API validation)
  API_PUBLIC_KEY: ""
  API_SECRET_KEY: ""


# These are the messages sent to the user
MESSAGES:


  message_1: >

    ---

    Please enter exchange to pull OHLCV data from.

    Examples: "binance", "bitfinex" (Quotes not needed in entry)

  message_1_error_handler:
    "---\n\nERROR: Exchange `%s`  is unavailable.\n\n"


  message_2: >

    ---

    Please enter API public key (press `Enter` if None).


  message_3: >

      ---

      Please enter API private key (press `Enter` if None).


  message_4: >

    ---

    Please enter ticker of interest.


  message_4_error_handler:
    "---\n\nERROR: Ticker `%s`  is not available on %s.\n\n"


  message_5: >

    ---

    Please enter your candle interval as an abbreviation.

    Examples:  "5m", "1h", "4h", "1d"  (Quotes not needed in entry)

  message_5_error_handler:
    "---\n\nERROR: Candle interval `%s`  does not exist.\n\n"


  message_6: >

    ---

    Please enter start date (Leave empty for 500 most-recent OHLCV prices).

    Example: "2019-01-01 00:00:00"

  message_6_error_handler1:
    "---\n\nERROR: Start date `%s`  cannot be parsed.\n\n"

  message_6_error_handler2:
    "---\n\nERROR: State date not available.  First date with price history is %s"


  message_7: >

    ---

    Please enter end date.  (Leave empty for current date)

    Example: "2019-12-31 23:00:00"

  message_7_error_handler:
    "---\n\nERROR: End date `%s`  cannot be parsed.\n\n"
